08_基本課題完了
HisanobuOgawa/elites-crm02 pull request #1
Opened 2016-10-30 07:35 UTC by HisanobuOgawa

08_基本課題が完了致しました｡レビューをお願い致します｡

2016-10-30 10:09 UTC, ericallfesta commented
'app/controllers/comments_controller.rb'
での
'@comments = @customer.comments'
処理と
'app/controllers/customers_controller.rb"
での
'@comments = @customer.comments'
処理が被っているので
今の段階だとエラーは起きませんが
今後エラーの原因箇所の判明に時間がかかったりするので
避けましょう。

2016-10-30 10:10 UTC, ericallfesta requested changes
'@comments = @customer.comments'の重複

2016-11-02 02:53 UTC, HisanobuOgawa commented
お疲れ様です｡間違って2つPushしてしまいましたが､「08_基本課題修正」の方が､現状でございます｡お手数おかけ致しますが､ご確認のほど何卒宜しくお願い致します｡

2016-11-02 04:21 UTC, HisanobuOgawa commented
再修正致しました｡ご確認のほど何卒宜しくお願い致します｡

2016-11-05 14:44 UTC, merged